### ISSUE TITLE
115里面导出下载的按钮大几率不出现

### ISSUE THREAD

**Issue by qiqian** [bluebabes/115#1]
以前挺好用的，最近“导出下载”这个按钮经常莫名消失，重启chrome，设置插件页面访问权限，都试了一下，不管用
很偶然的情况下，刷新115页面会出来按钮，这时下载到aria2是正常的，但问题是这个按钮90%以上的时候都不存在！
作为一个付费使用的插件，有这种基础可用性问题，太让人懊恼了

**Comment by qiqian** [comment]
Chrome Version 91.0.4472.77 (Official Build) (64-bit)
115 version  1.5.48

**Comment by bluebabes** [comment]
@qiqian

48 版本可以通过，左上角点击 “文件”  展示

**Comment by bluebabes** [comment]
<img width="764" alt="刷不出来导出的看这图(1)" src="https://user-images.githubusercontent.com/3329261/122547211-63858800-d062-11eb-8f70-0237ca111a2e.png">

**Comment by bluebabes** [comment]
@qiqian 非常抱歉，不是不解决这个问题，是我这无法重现这个问题

今天远程了一个用户，定位到问题了， 你可以试试 release 的 52 版本

**Comment by DylanL089** [comment]
Chrome Version 91.0.4472.106 (Official Build) (64-bit)
115 version 1.5.52
仍旧没有 “导出下载” 的选项 

![image](https://user-images.githubusercontent.com/86151413/122639886-0a375a80-d12f-11eb-9360-5802237d8819.png)

**Comment by bluebabes** [comment]
检查 设置里面 是否已经开启了 aria 开关__

**Comment by bluebabes** [comment]
@qiqian  试试 https://github.com/bluebabes/115/releases/tag/v1.5.53
