### ISSUE TITLE
错误描述: HTTP 返回头无效或无法识别.

### ISSUE THREAD

**Issue by ritech** [bluebabes/115#1]
115 在下载大文件和小文件的cdn服务器好像不太一样，
小文件是
下载地址: http://cdnfhnfile.115.com/
大文件是
下载地址: http://cdnfhn210.115.com/ 这个210的数字可能会变

在队列里面 小文件的地址在一定时间后地址貌似变化了， 造成下载失败，大文件地址反而一直正常（如果小文件在队列靠前位置，会被正确下载）
<img width="873" alt="0399202C-3A77-48D6-A060-7D41CBB3207D" src="https://user-images.githubusercontent.com/11290395/93706855-02756600-fb5d-11ea-8c81-9be01beba61e.png">

**Comment by bluebabes** [comment]
这个下载地址是 115 给的 ，不是固定的
